# Site settings
title: Find Courses - Active Coala
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/course" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

excerpt_separator: </teaser>

permalink: pretty

sass:
    sass_dir: /_includes
  
collections:
  courses:
    output: true
  schools:
    output: true
  places:
    output: true
  
defaults:
 -
    scope:
      type: "courses"
    values:
      layout: "course-layout"
 -
    scope:
      type: "schools"
    values:
     layout: "school-layout"  
 -
    scope:
      type: "places"
    values:
     layout: "default"
 -
    scope:
      path: "categories"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "categories-layout" # overrides previous default layout
      pagename: categories