# Site settings
title: Phed Courses
description: "Δες το πρόγραμμα της εξεταστικής σου και όχι μόνο"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "thestudens.xyz"


# Build settings
markdown: kramdown

excerpt_separator: </teaser>

permalink: pretty

sass:
    sass_dir: /_includes
  